MyBlog/MyBlog/Controllers/InfoController.cs
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using MyBlog.Models;
using System;

namespace MyBlog.Controllers
{
    public class InfoController : Controller
    {
        public IActionResult AboutUs()
        {
            ViewBag.CompanyName = "Yoga Blog";
            ViewBag.CurrentDate = DateTime.Now.ToString();
            return View();
        }
        public IActionResult ContactUs()
        {
            return View();
        }
    }
}

MyBlog/MyBlog/Controllers/PostController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using Microsoft.AspNetCore.Mvc;
using MyBlog.Models;
using MyBlog.Services;
using MyBlog.Services.Interfaces;

namespace MyBlog.Controllers
{
    public class PostController : Controller
    {
        public IPostService PostService { get; set; }
        public PostController(IPostService postservice)
        {
            PostService = postservice;
        }
        public IActionResult Overview(string title)
        {
            var posts = PostService.GetByTitle(title);
            return View(posts);
        }

        public IActionResult Details(int id)
        {
            var post = PostService.GetById(id);

            return View(post);
        }

        [HttpGet]
        public IActionResult Create()
        {
            Post post = new Post();
            return View(post);
        }

        [HttpPost]
        public IActionResult Create(Post post) 
        {
            if (ModelState.IsValid)
            {
                PostService.CreatePost(post);
                return RedirectToAction("Overview");
            }
            else
            {
                return View(post);
            }
        }
    }
}

MyBlog/MyBlog/Views/Info/AboutUs.cshtml
@model MyBlog.Models.Post;

@{
    Layout = "_Layout";
}

<h1>Hello from our about</h1>
<p>We are @ViewBag.CompanyName</p>
<p>Current time is: @ViewBag.CurrentDate</p>

MyBlog/MyBlog/Views/Info/ContactUs.cshtml
@{
    Layout = "_Layout";
}

<h1>Hey, here are some information how you can reach us</h1>
<p>Email: yoga@mybloog.com</p>
<p>Phone: +38931123123</p>

MyBlog/MyBlog/Views/Post/Create.cshtml
@model MyBlog.Models.Post;

@addTagHelper *, Microsoft.AspNetCore.Mvc.TagHelpers

@{
    Layout = "_Layout";
    ViewBag.Title = "Create";
}


<p>New Post</p>

<div class="row">
    <div class="col-md-4">
        <form asp-controller="Post" asp-action="Create" method="post">
            @*<div asp-validation-summary="All" class="text-danger"></div>*@
            <div class="form-group">
                <label asp-for="Title" class="control-label">Title</label>
                <input asp-for="Title" class="form-control" />
                <span asp-validation-for="Title" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Description" class="control-label">Description</label>
                <input asp-for="Description" class="form-control" />
                <span asp-validation-for="Description" class="text-danger"></span>

            </div>
            <div class="form-group">
                <label asp-for="ImageUrl" class="control-label">Image URL</label>
                <input asp-for="ImageUrl" class="form-control" />
                <span asp-validation-for="ImageUrl" class="text-danger"></span>

            </div>
            <div class="form-group">
                <label asp-for="Editor" class="control-label">Director</label>
                <input asp-for="Editor" class="form-control" />
                <span asp-validation-for="Editor" class="text-danger"></span>

            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

MyBlog/MyBlog/Views/Post/Details.cshtml
@model MyBlog.Models.Post;

@{
   Layout = "_Layout";
    ViewBag.Title = "Details";
 }

    <div id="container" style="width: 70%; margin: 0 auto;">
        <img src="@Model.ImageUrl"  style="width:100%" />
        <h1>@Model.Title</h1>
        <p>@Model.Description</p>
        <h5>@Model.Editor</h5>
    </div>

MyBlog/MyBlog/Views/Post/Overview.cshtml
@model List<MyBlog.Models.Post>;

@addTagHelper *, Microsoft.AspNetCore.Mvc.TagHelpers
@{
    Layout = "_Layout";
    ViewBag.Title = "Home";
}



<div class="row">
    @foreach (var post in Model)
    {
        <div class="col-md-12">
            <div class="card" style="width: 50%; margin: 0 auto; margin-top:20px;">
                <img class="card-img-top" src="@post.ImageUrl" alt="card image cap">
                <div class="card-body">
                    <h5 class="card-title"> @post.Title </h5>
                    <p class="card-text">@post.Description</p>
                    <a href="/Post/Details/@post.Id" class="btn btn-primary">See more</a>
                </div>
            </div>

        </div>
    }

</div>

MyBlog/MyBlog/Views/Shared/_Layout.cshtml
@addTagHelper *, Microsoft.AspNetCore.Mvc.TagHelpers
@{
    var homeActive = ViewBag.Title == "Home" ? "active" : "";
    var aboutIsActive = ViewBag.Title == "About Us" ? "active" : "";
    var contactIsActive = ViewBag.Title == "Contact Us" ? "active" : "";
    var createIsActive = ViewBag.Title == "Create" ? "active" : "";
}
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <link href="https://fonts.googleapis.com/css2?family=Dancing+Script&family=Sacramento&family=Tangerine:wght@700&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="~/css/style.css" />
</head>
<body>
    <h1 style="text-align:center;font-family: 'Tangerine', cursive;">Yoga Blog <img src="https://img.icons8.com/cotton/64/000000/lotus--v1.png" style="width:40px;height:40px;margin-bottom:20px;" /></h1>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav mr-auto">

                <li class="nav-item @homeActive">
                    <a class="nav-link" asp-controller="Post" asp-action="Overview">Home</a>
                </li>
                <li class="nav-item @aboutIsActive">
                    <a class="nav-link" asp-controller="Info" asp-action="AboutUs">About Us</a>
                </li>
                <li class="nav-item @contactIsActive">
                    <a class="nav-link" asp-controller="Info" asp-action="ContactUs">Contact Us</a>
                </li>
                <li class="nav-item @contactIsActive">
                    <a class="nav-link" asp-controller="Post" asp-action="Create">Create</a>
                </li>
                @*<li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    Dropdown
                </a>
                <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                    <a class="dropdown-item" href="#">Action</a>
                    <a class="dropdown-item" href="#">Another action</a>
                    <div class="dropdown-divider"></div>
                    <a class="dropdown-item" href="#">Something else here</a>
                </div>
            </li>*@




            </ul>


            <form class="form-inline my-2 my-lg-0" asp-controller="Post" asp-action="Overview">
                <input name="Title" class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
                <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
            </form>
        </div>
    </nav>
    <div class="container" style="margin-top:40px;">

        @RenderBody()
    </div>
</body>
</html>